# Generated by Django 5.0.4 on 2024-04-12 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_course_registration_app', '0003_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='project',
            name='languages_used',
        ),
        migrations.RemoveField(
            model_name='project',
            name='student',
        ),
        migrations.RemoveField(
            model_name='project',
            name='topic',
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='students',
            field=models.ManyToManyField(related_name='projects', to='student_course_registration_app.student'),
        ),
    ]
