# Generated by Django 5.0.4 on 2024-04-12 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_course_registration_app', '0004_remove_project_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='students',
        ),
        migrations.AddField(
            model_name='project',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='languages_used',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='topic',
            field=models.CharField(default='', max_length=100),
        ),
    ]
