# Generated by Django 5.0.4 on 2024-04-12 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_course_registration_app', '0005_remove_project_description_remove_project_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='project',
            field=models.ManyToManyField(blank=True, related_name='students', to='student_course_registration_app.project'),
        ),
    ]
